# Generated by Django 3.2.5 on 2022-08-17 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ans_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_content', models.TextField(verbose_name='回答文本')),
            ],
        ),
        migrations.CreateModel(
            name='ask_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='问题题目')),
                ('ask_intro', models.TextField(verbose_name='问题简介')),
            ],
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('intro', models.CharField(max_length=200, verbose_name='个人简介')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('focus_ask', models.ManyToManyField(to='app1.ask_list', verbose_name='关注问题')),
                ('vote_ans', models.ManyToManyField(to='app1.ans_list', verbose_name='赞同回答')),
            ],
        ),
        migrations.AddField(
            model_name='ask_list',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_list'),
        ),
        migrations.AddField(
            model_name='ans_list',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_list'),
        ),
        migrations.AddField(
            model_name='ans_list',
            name='thisask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ask_list'),
        ),
    ]
