# Generated by Django 3.2.5 on 2022-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_list',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='user_list',
            name='focus_ask',
            field=models.ManyToManyField(blank=True, null=True, to='app1.ask_list', verbose_name='关注问题'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='vote_ans',
            field=models.ManyToManyField(blank=True, null=True, to='app1.ans_list', verbose_name='赞同回答'),
        ),
    ]
