# Generated by Django 3.2.5 on 2022-08-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220817_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=200, verbose_name='评论')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_list')),
                ('thiscomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ans_list')),
            ],
        ),
    ]
