# Generated by Django 3.2.5 on 2022-08-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_comment_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans_list',
            name='see_num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
