# Generated by Django 3.2.5 on 2022-08-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_ans_list_see_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_list',
            name='ask_kind',
            field=models.SmallIntegerField(blank=True, choices=[(1, '学习'), (2, '生活'), (3, '吐槽'), (4, '选课')], null=True, verbose_name='问题标签'),
        ),
    ]
